CREATE TABLE `OFFRE` (
	`o_id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`o_titre` VARCHAR(255) NOT NULL,
	`o_salaire` FLOAT NOT NULL,
	`o_description` VARCHAR(255) NOT NULL,
	`o_type_contrat` VARCHAR(255) NOT NULL,
	`o_statut` BOOLEAN NOT NULL,
	PRIMARY KEY(`o_id`)
);


CREATE TABLE `USER` (
	`u_id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`u_nom` VARCHAR(255) NOT NULL,
	`u_mail` VARCHAR(255) NOT NULL,
	`u_mdp` VARCHAR(255) NOT NULL,
	`u_role` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`u_id`)
) COMMENT='
';


CREATE TABLE `ROLE` (
	`r_id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`r_label` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`r_id`)
);


CREATE TABLE `PERMISSIONS` (
	`p_id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`p_label` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`p_id`)
);


CREATE TABLE `SKILLS` (
	`s_id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`s_label` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`s_id`)
);


ALTER TABLE `USER`
ADD FOREIGN KEY(`u_id`) REFERENCES `OFFRE`(`o_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `USER`
ADD FOREIGN KEY(`u_role`) REFERENCES `ROLE`(`r_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ROLE`
ADD FOREIGN KEY(`r_id`) REFERENCES `PERMISSIONS`(`p_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `SKILLS`
ADD FOREIGN KEY(`s_id`) REFERENCES `USER`(`u_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `SKILLS`
ADD FOREIGN KEY(`s_id`) REFERENCES `OFFRE`(`o_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;